const ADDUSER = "ADDUSER"
const ADDEVENTS = "ADDEVENTS"
const LOGOUT = "LOGOUT"
const ADDEVENT = "ADDEVENT"
const EDITEVENT = "EDITEVENT"


export {
	ADDUSER,
	ADDEVENTS,
	LOGOUT,
	ADDEVENT,
	EDITEVENT
}