const ADDUSER = "ADDUSER"
const ADDEVENTS = "ADDEVENTS"
const LOGOUT = "LOGOUT"
const ADDEVENT = "ADDEVENT"
const EDITEVENT = "EDITEVENT"
const SETERROR = "SETERROR"
const CLEARERROR = "CLEARERROR"
const LEAVEEVENT = "LEAVEEVENT"
const JOINEVENT = "JOINEVENT"
const ADDUSERS = "ADDUSERS"
const PAGES = ["events", "profile", "create", "users"]


export {
	ADDUSER,
	ADDEVENTS,
	LOGOUT,
	ADDEVENT,
	EDITEVENT,
	SETERROR,
	CLEARERROR,
	LEAVEEVENT,
	JOINEVENT,
	PAGES,
	ADDUSERS
}