const ADDUSER = "ADDUSER"
const ADDEVENTS = "ADDEVENTS"
const LOGOUT = "LOGOUT"
const ADDEVENT = "ADDEVENT"
const EDITEVENT = "EDITEVENT"
const SETERROR = "SETERROR"
const CLEARERROR = "CLEARERROR"


export {
	ADDUSER,
	ADDEVENTS,
	LOGOUT,
	ADDEVENT,
	EDITEVENT,
	SETERROR,
	CLEARERROR
}